In [1]:
import numpy as np

In [3]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.ones((2, 3)) * 10

array([[10., 10., 10.],
       [10., 10., 10.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.random()

0.525591274615618

In [15]:
np.random.random((2, 3))

array([[0.71165385, 0.76242443, 0.59546599],
       [0.52838662, 0.32777176, 0.73176491]])

In [17]:
np.random.randn(2, 3)

array([[-1.27898161,  0.91869695,  1.01159969],
       [-2.92740199, -0.4842197 ,  0.79641128]])

In [19]:
R = np.random.randn(10000)

In [20]:
R.mean()

0.006157770417883251

In [21]:
R

array([ 1.33277284,  0.21266964, -0.96358949, ..., -1.04912935,
       -0.35020798,  1.94332264])

In [22]:
np.mean(R)

0.006157770417883251

In [23]:
R.var()

0.993253252679708

In [25]:
R.std()

0.9966209172397035

In [26]:
np.sqrt(R.var())

0.9966209172397035

In [27]:
R = np.random.randn(10000, 3)

In [28]:
R

array([[-2.21490458,  0.18370644, -1.72214097],
       [ 2.13248007, -0.9510112 ,  0.72337771],
       [ 0.26720103, -1.44571715, -0.32291057],
       ...,
       [-0.82371638, -1.43506816,  0.45580726],
       [-1.02613579, -1.74447992,  0.24555035],
       [ 0.8521775 , -0.80512943, -0.43569343]])

In [29]:
R.mean(axis=0)

array([ 0.00314748, -0.01384069,  0.00042507])

In [32]:
R.mean(axis=1).shape

(10000,)

In [33]:
np.cov(R)

array([[ 1.60473419, -1.88026337, -1.08988466, ..., -0.73993541,
        -0.81484692, -0.88565654],
       [-1.88026337,  2.38284434,  1.33221846, ...,  0.54136315,
         0.62585942,  1.25726882],
       [-1.08988466,  1.33221846,  0.75716917, ...,  0.40253686,
         0.45240784,  0.66893732],
       ...,
       [-0.73993541,  0.54136315,  0.40253686, ...,  0.93105693,
         0.97153546,  0.01064895],
       [-0.81484692,  0.62585942,  0.45240784, ...,  0.97153546,
         1.01557073,  0.04798965],
       [-0.88565654,  1.25726882,  0.66893732, ...,  0.01064895,
         0.04798965,  0.75696012]])

In [34]:
np.cov(R.T)

array([[1.00214012, 0.01167187, 0.01651522],
       [0.01167187, 0.99863891, 0.00344517],
       [0.01651522, 0.00344517, 1.00192863]])

In [35]:
np.cov(R, rowvar=False)

array([[1.00214012, 0.01167187, 0.01651522],
       [0.01167187, 0.99863891, 0.00344517],
       [0.01651522, 0.00344517, 1.00192863]])

In [36]:
np.random.randint(0, 10, size=(3, 3))

array([[8, 3, 0],
       [1, 0, 6],
       [5, 6, 3]])

In [37]:
np.random.choice(10, size=(3, 3))

array([[8, 9, 4],
       [2, 9, 8],
       [6, 1, 3]])