In [1]:
import numpy as np

In [3]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [5]:
L[0]

[1, 2]

In [8]:
L[0][1]

2

In [10]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [12]:
A[0][1]

2

In [14]:
A[0,1]

2

In [16]:
A[:,0]

array([1, 3])

In [21]:
A.T

array([[1, 3],
       [2, 4]])

In [22]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [24]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [27]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [39]:
B.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [41]:
np.linalg.det(A)

-2.0000000000000004

In [42]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [45]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [46]:
np.trace(A)

5

In [47]:
np.diag(A)

array([1, 4])

In [50]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [53]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [59]:
Lam, V = np.linalg.eig(A)
V[:,0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [62]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [66]:
np.allclose(V @ np.diag(Lam), A @ V)

True