In [17]:
import numpy as np

In [18]:
# Arrays vs Matrices

$$ \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} $$

In [19]:
A = np.array([[1,2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [20]:
L = [[1, 2], [3, 4]]
L

[[1, 2], [3, 4]]

In [21]:
LA = np.array(L)
LA 

array([[1, 2],
       [3, 4]])

In [22]:
L[0][1]

2

In [23]:
A[0][1]

2

In [24]:
A[0, 1]

2

In [25]:
L[0, 1]

TypeError: list indices must be integers or slices, not tuple

In [26]:
M = np.matrix([[1, 2], [3, 4]])
M

matrix([[1, 2],
        [3, 4]])

In [27]:
A.dot(A)

array([[ 7, 10],
       [15, 22]])

In [28]:
M.dot(M)

matrix([[ 7, 10],
        [15, 22]])

In [29]:
A.dot(M)

matrix([[ 7, 10],
        [15, 22]])

In [30]:
M.dot(A)

matrix([[ 7, 10],
        [15, 22]])

In [31]:
v = np.array([1, 2])
v

array([1, 2])

In [32]:
v2 = np.matrix([1, 2])
v2

matrix([[1, 2]])

In [33]:
v.shape

(2,)

In [34]:
v2.shape

(1, 2)

In [35]:
v3 = np.matrix([[1], [2]])
v3

matrix([[1],
        [2]])

In [36]:
v3.shape

(2, 1)

In [37]:
v3.T

matrix([[1, 2]])

In [38]:
v3.T.shape

(1, 2)

In [39]:
v3.T @ v3

matrix([[5]])

In [40]:
# Matrix Vector Product

A = np.array([[1, 2], [3, 4]])
y = np.array([-15, 7])


In [41]:
A.dot(y)

array([ -1, -17])

In [42]:
A = np.array([[1, 2], [3, 4]])
x = np.array([5, 10])

In [43]:
A.dot(x)

array([25, 55])

In [44]:
# Matrix Matrix Product is not commutative, as in they do not generate the same answer
# 2 * 3 = 6 == 3 * 2 = 6
# however in matrix:
# A * B != B * A 

A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 3], [2, 1]])
A.dot(B)

array([[ 8,  5],
       [20, 13]])

In [45]:
B.dot(A)

array([[13, 20],
       [ 5,  8]])

In [46]:
# they have different results...

In [47]:
# Linear Property



$$ T(\alpha x + \beta y) = \alpha T(x) + \beta T(y) $$

In [48]:
A = np.array([[1, 2], [3, 4]])
x = np.array([5, 10])
y = np.array([-15, 7])

# randomly chosen, no reference
alpha = 0.9
beta = -0.5

In [49]:
A.dot(alpha * x + beta * y)

array([23., 58.])

In [50]:
alpha * A.dot(x) + beta * A.dot(y)

array([23., 58.])

In [51]:
# Outer Product

x = np.array([5, 10])
y = np.array([-15, 6])


In [52]:
x.dot(y)

-15

In [53]:
np.inner(x, y)

-15

In [54]:
np.outer(x, y)

array([[ -75,   30],
       [-150,   60]])

In [55]:
x2 = x.reshape(2, 1)
x2

array([[ 5],
       [10]])

In [56]:
y2 = y.reshape(1, 2)
y2

array([[-15,   6]])

In [57]:
x2.dot(y2)

array([[ -75,   30],
       [-150,   60]])

In [58]:
x3 = np.matrix(x2)
x3

matrix([[ 5],
        [10]])

In [59]:
y3 = np.matrix(y2.T)
y3

matrix([[-15],
        [  6]])

In [60]:
x3 @ y3.T


matrix([[ -75,   30],
        [-150,   60]])