In [1]:
import numpy as np

In [2]:
# Checking the rank of a matrix

In [4]:
# Simple example
A = np.array([[1, 2,], [1, 1]])
np.linalg.matrix_rank(A)

2

In [5]:
# What if one row/col is *almost* a constant multiple of another?
A = np.array([[1, 1.0000001], [1, 1]])
np.linalg.matrix_rank(A)

2

In [10]:
# we can find the rank by looking at how many non-zero values are in S
A = np.array([[1, 2], [1, 1]])
U, S, VT = np.linalg.svd(A)
S

# Because both values are bigger than 0, this is rank 2, based on number of values bigger than 0

array([2.61803399, 0.38196601])

In [11]:
U

array([[-0.85065081, -0.52573111],
       [-0.52573111,  0.85065081]])

In [8]:
VT

array([[-0.52573111, -0.85065081],
       [ 0.85065081, -0.52573111]])

In [12]:
A = np.array([[1, 2], [2, 4]])
U, S, VT = np.linalg.svd(A)
S

# If values are less than 10e-10 then we cosnider this less than 0
# So this is rank 1

array([5.00000000e+00, 1.98602732e-16])

In [13]:
# Matrix Decompositions

L = np.array([[1, 0], [2, 1]])
A = L @ L.T
A

array([[1, 2],
       [2, 5]])

In [14]:
np.linalg.cholesky(A)

array([[1., 0.],
       [2., 1.]])

In [15]:
import scipy
A = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
P, L, U = scipy.linalg.lu(A) # A = P @ L @ U

In [16]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [17]:
L

array([[1. , 0. , 0. ],
       [0.2, 1. , 0. ],
       [0.6, 0.5, 1. ]])

In [18]:
U

array([[5. , 6. , 7. ],
       [0. , 0.8, 1.6],
       [0. , 0. , 0. ]])

In [19]:
A = np.array([[1, 2], [3, 4], [5, 6]])
P, L, U = scipy.linalg.lu(A)

In [20]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [21]:
L

array([[1. , 0. ],
       [0.2, 1. ],
       [0.6, 0.5]])

In [22]:
U

array([[5. , 6. ],
       [0. , 0.8]])

In [23]:
A = np.array([[1, 2], [3, 4], [5, 6]])
Q, R = np.linalg.qr(A)

In [24]:
Q

array([[-0.16903085,  0.89708523],
       [-0.50709255,  0.27602622],
       [-0.84515425, -0.34503278]])

In [25]:
R

array([[-5.91607978, -7.43735744],
       [ 0.        ,  0.82807867]])

In [26]:
Q @ Q.T

array([[ 0.83333333,  0.33333333, -0.16666667],
       [ 0.33333333,  0.33333333,  0.33333333],
       [-0.16666667,  0.33333333,  0.83333333]])

In [27]:
Q.T @ Q

array([[1.00000000e+00, 6.18439648e-17],
       [6.18439648e-17, 1.00000000e+00]])

In [28]:
# Frobenius Norm and Trace

In [29]:
A = np.array([[1, 2], [3, 4], [5, 6]])
np.linalg.norm(A)

9.539392014169456

In [30]:
np.sqrt(np.trace(A @ A.T))

9.539392014169456

In [31]:
np.sqrt(np.trace(A.T @ A))

9.539392014169456

In [32]:
# Investigating SVD

In [33]:
A = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]])
U, S, VT = np.linalg.svd(A)

In [34]:
U

array([[-0.18923073, -0.81497959,  0.37684105, -0.39748059],
       [-0.36846753, -0.40525508, -0.2061902 ,  0.81085486],
       [-0.54770432,  0.00446943, -0.71814276, -0.42926795],
       [-0.72694112,  0.41419393,  0.54749191,  0.01589368]])

In [35]:
S

array([1.91491774e+01, 1.14411715e+00, 1.08189867e-15])

In [36]:
VT

array([[-0.47635167, -0.57203953, -0.66772738],
       [ 0.77873129,  0.07812881, -0.62247367],
       [-0.40824829,  0.81649658, -0.40824829]])

In [37]:
U @ U.T

array([[ 1.00000000e+00, -9.41122854e-17,  8.66386741e-18,
        -1.52645594e-18],
       [-9.41122854e-17,  1.00000000e+00,  2.76362030e-17,
         1.59558691e-17],
       [ 8.66386741e-18,  2.76362030e-17,  1.00000000e+00,
         1.98482004e-17],
       [-1.52645594e-18,  1.59558691e-17,  1.98482004e-17,
         1.00000000e+00]])

In [38]:
z = U @ U.T
I = np.eye(len(z))
np.allclose(z, I)

True

In [39]:
np.linalg.matrix_rank(A.T @ A)

2

In [40]:
np.linalg.matrix_rank(A @ A.T)


2

In [41]:
np.linalg.matrix_rank(A)

2