In [1]:
import tensorflow as tf

In [2]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Things you should automatically know and have memorized
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

In [4]:
# Make some data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [5]:
# Make an RNN
M = 5 # number of hidden units
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [6]:
# Get the output
Yhat = model.predict(X)
print(Yhat)

1/1 [==============================] - 1s 1s/step
[[0.03389475 0.44566476]]


In [7]:
# See if we can replicate this output
# Get the weights first
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [8]:
# See what's returned
model.layers[1].get_weights()

[array([[ 0.2938903 ,  0.2596205 ,  0.8527456 , -0.42677793, -0.6758355 ],
        [ 0.44375628, -0.72849196,  0.76333636,  0.08142483, -0.58177036],
        [ 0.52590364,  0.50432163,  0.7207789 , -0.35343623,  0.14293271]],
       dtype=float32),
 array([[-0.04767585, -0.62414753,  0.01330619, -0.28579068,  0.72547466],
        [ 0.23947012,  0.61423755,  0.558751  , -0.10779548,  0.49147132],
        [ 0.03992498,  0.31556448, -0.48832193, -0.81179917, -0.03672726],
        [-0.8150451 ,  0.33143824, -0.25810727,  0.22923519,  0.3266222 ],
        [ 0.52391654,  0.15401292, -0.6185004 ,  0.44174325,  0.3522948 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [9]:
# Check their shapes
# Should make sense
# First output is input > hidden
# Second output is hidden > hidden
# Third output is bias term (vector of length M)
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [10]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [13]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo # we only care about this value on the last iteration
  Yhats.append(y)
  
  # important: assign h to h_last
  h_last = h

# print the final output
print(Yhats[-1])

[0.03389485 0.44566479]
